services:
  apiescuela-backend:
    container_name: apiescuela-backend-uteq
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    image: apiescuela-backend-image
    command: go run main.go
    restart: always
    volumes:
      - ./ApiEscuela:/home/app
      - ./ApiEscuela/assets/images:/home/app/assets/images
    ports:
      - "3200:3000"
    env_file:
      - .env
    networks:
      - escuela_network
  frontedescuela-frontend:
    container_name: frontedescuela-frontend-uteq
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        - VITE_API_URL=https://aplicaciones.uteq.edu.ec:9602
    command: npx serve -s dist -l 5173
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - apiescuela-backend
    networks:
      - escuela_network
  nginxescuelauteq:
    container_name: nginxescuelauteq-uteq
    image: nginx
    tty: true
    ports:
      - "9601:443"
      - "9602:444"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl/
      - ./nginx/html/:/var/www/html
      - ./nginx/logs:/etc/nginx/logs
    restart: always
    depends_on:
      - frontedescuela-frontend
      - apiescuela-backend
    networks:
      - escuela_network

networks:
  escuela_network:
    driver: bridge
